### ISSUE TITLE
Test Gnosis Chain Payment Permit

### ISSUE THREAD

**Issue by pavlovcik** [ubiquibot/gnosis-chain#1]
This is used as an example for a Gnosis Chain payment example. This should remain unclaimed.

**Comment by pavlovcik** [comment]
> autoPayMode

We need to update our `ubiquibot-config.yml` in our `@ubiquity/ts-template` I assume the property name was changed.

**Comment by pavlovcik** [comment]
@rndquu would you mind helping me to generate a payment permit on gnosis chain that will remain unclaimed so that I can link it as reference in https://github.com/ubiquity/pay.ubq.fi/issues/69

**Comment by pavlovcik** [comment]
I used another example but there seems to be an issue with the config on this repository. I could use your help to solve the problem on this @rndquu

**Comment by rndquu** [comment]
> I used another example but there seems to be an issue with the config on this repository. I could use your help to solve the problem on this @rndquu

Hard to say, I will check it in the morning
